
spring:
  application:
    name: mybatis-test
  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 20000
      driver-class-name: org.mariadb.jdbc.Driver
      max-lifetime: 0
      maximum-pool-size: 1000
      minimum-idle: 0
    url: jdbc:mariadb://localhost:3306/employeebackend
    username: root
    password: a22607226
server:
  port: 8118
mybatis:
  mapper-locations: classpath:mapper/*.xml